# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, unique=True)),
                ('topic', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField()),
                ('link1', models.CharField(max_length=250)),
                ('link2', models.CharField(max_length=250)),
                ('link3', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to=b'')),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
    ]
